### PR TITLE
Set checked to false on indeterminate changed

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Connected to #42

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/43)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Test

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43#-:-KxvwCVRAcY0VrjQiJlW:bb74njr)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43#-:-KxwmdAn84k-2RgjdNRg:bnfp4nl)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/vaadin-checkbox_test.html, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43#-Kxwq10JWjAlt281Ikvs:-Kxwq10K6q-HJxf4a8fd:b-91y58a) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3b06d6a8f5b1a63046cc2890000c56937438bccb/test/vaadin-checkbox_test.html#L139)):*
> ```HTML
> 
>       it('should not be checked when indeterminate is true', () => {
>         vaadinCheckbox.checked = false;
> ```

Consider:
```javascript
vaadinCheckbox.checked = true;
vaadinCheckbox.indeterminate = true;
```

What to expect? Maybe have a test for that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-checkbox.html, line 197 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43#-Kxwqlf5uLD2lQOaN9gt:-Kxwqlf5uLD2lQOaN9gu:bhdrk2n) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3b06d6a8f5b1a63046cc2890000c56937438bccb/vaadin-checkbox.html#L197)):*
> ```HTML
> 
>           if (!indeterminate) {
>             this.checked = true;
> ```

Missing tests for this `indeterminate = false;` case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-checkbox.html, line 197 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43#-Kxwqlf5uLD2lQOaN9gt:-Ky0sNua_jpEL07IFYif:bqmjwcz) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3b06d6a8f5b1a63046cc2890000c56937438bccb/vaadin-checkbox.html#L197)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Missing tests for this `indeterminate = false;` case.
</blockquote></details>

Added.

---

*[test/vaadin-checkbox_test.html, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43#-Kxwq10JWjAlt281Ikvs:-Ky0sOjhs9Gca-kXd-46:bqmjwcz) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3b06d6a8f5b1a63046cc2890000c56937438bccb/test/vaadin-checkbox_test.html#L139)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Consider:
```javascript
vaadinCheckbox.checked = true;
vaadinCheckbox.indeterminate = true;
```

What to expect? Maybe have a test for that?
</blockquote></details>

Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43)*

**Comment by platosha** [comment]
LGTM

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/43#-:-KyKQ6YnWBvvFhY8NeKw:bb6ywmx)*

**Pull request merged**
