### PR TITLE
Fixes checkbox not working on iPhone

### LINKED ISSUE #5: Checkbox doesn't work on iPhone
Can't click any checkbox, live demo: http://flow.app.fi/demo-flow-components-0.1.16-SNAPSHOT/vaadin-checkbox

### PR DESCRIPTION
**Pull request by gatanaso**
Fixes #5
Fixes checkbox not working on iPhone.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/6)

### CODE REVIEW

**Comment by limonte** [comment]
Is it possible to prove the bug with the test?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/6#-:-KrZxZoSuMnONISTA2iy:b-ond79f)*

**Comment by YuriyVaadin** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-checkbox.html, line 210 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/6#-KrerxsAx5BEdjXKeyq3:-KrerxsAx5BEdjXKeyq4:bly3mje) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/8266bcd4b4f14d795c981755524d7c779179161b/vaadin-checkbox.html#L210)):*
> ```HTML
>         _handleClick(e) {
>           if (!this.disabled && !this.indeterminate) {
>             if (e.composedPath()[0] !== this.$.label.querySelector('#nativeCheckbox')) {
> ```

Is it possible to replace `this.$.label.querySelector('#nativeCheckbox')` with `this.$.nativeCheckbox`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/6)*

**Comment by gatanaso** [comment]
I was unable to prove the bug with a test on iPhone.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-checkbox.html, line 210 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/6#-KrerxsAx5BEdjXKeyq3:-KreuDF7Kdvzvqx07JXw:bli0uze) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/8266bcd4b4f14d795c981755524d7c779179161b/vaadin-checkbox.html#L210)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Is it possible to replace `this.$.label.querySelector('#nativeCheckbox')` with `this.$.nativeCheckbox`?
</blockquote></details>

Yes, good point. I will update and push the changes. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/6#-:-KreuI7Zfkugait1taeD:b-ww9g9)*

**Comment by limonte** [comment]
> I was unable to prove the bug with a test on iPhone.

For this particular case test could be skipped IMO.

:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/6#-:-Krey4a2Rmzl5OhMyGA-:b-8baae)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/6#-:-KreyJUW4bEZ1I6E4094:bnfp4nl)*

**Pull request merged**
