### PR TITLE
Added vaadin-checkbox-group MVP

### LINKED ISSUE #100: Checkbox group MVP
child of #98

- Basic functionality excluding the label and form validation APIs (see the epic for more info)
- Start working on top of `<vaadin-radio-group>` to keep the internals aligned
- Make sure it's compatible with P3

### PR DESCRIPTION
**Pull request by sohrabtaee**
Fixes #100

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[gulpfile.js, line 6 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG05zqlApCef9toshTA:-LG05zqlApCef9toshTB:b7xpnvm) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/6fb455b5752398b7cc2710972b094f21ee6bb1c5/gulpfile.js#L6)):*
> ```JavaScript
> var eslint = require('gulp-eslint');
> var htmlExtract = require('gulp-html-extract');
> var lec = require('gulp-line-ending-corrector');
> ```

Please revert. Changes that concern all components should go trough skeleton. The lint process should also only validate without side-effects.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)*

**Comment by tomivirkki** [comment]
Review status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @sohrabtaee and @tomivirkki)

---

*[vaadin-checkbox-group.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG07mPvCEeXiea3Lil1:-LG07mPwD2jAaugukw82:b-yrq9ad) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/1b5a61fe436e7a48a2877e6d2257f58d319e8963/vaadin-checkbox-group.html#L1)):*
> ```HTML
> <link rel="import" href="theme/lumo/vaadin-checkbox-group.html">
> ```

Missing an empty line

---

*[demo/index.html, line 15 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG08W5_7ELBoE9nFOoR:-LG08W5_7ELBoE9nFOoS:bc5v2jx) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/1b5a61fe436e7a48a2877e6d2257f58d319e8963/demo/index.html#L15)):*
> ```HTML
> 
>   <script src="./checkbox-demo.js"></script>
>   <link rel="import" href="../../iron-form/iron-form.html">
> ```

All these need to be added to bower.json as devDependencies

---

*[src/vaadin-checkbox-group.html, line 164 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG09KaFCO8TJp2MDuwb:-LG09KaFCO8TJp2MDuwc:bv8srtn) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/1b5a61fe436e7a48a2877e6d2257f58d319e8963/src/vaadin-checkbox-group.html#L164)):*
> ```HTML
>     })();
>   </script>
> </dom-module>
> ```

Needs a new line

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)*

**Comment by tomivirkki** [comment]
*[src/vaadin-checkbox-group.html, line 97 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG0U5Jl6qDVmE9THWL4:-LG0U5Jm4jAjxz7LhIvj:bs3rv7v) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/ff813d2a976e5d90ecfbbf69e47a91e729480aff/src/vaadin-checkbox-group.html#L97)):*
> ```HTML
> 
>             this._filterCheckboxes(info.removedNodes).forEach(checkbox => {
>               checkbox.removeEventListener('checked-changed', checkedChangedListener);
> ```

The coverage report fails because these two lines aren't tested

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)*

**Comment by manolo** [comment]
Please check why coverage fails and why polymer 3 conversion build fails. We need the PR green

---

Review status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @sohrabtaee and @tomivirkki)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-:-LG4HsOzBLS_-fZQ63O7:be8vw0p)*

**Comment by YuriyVaadin** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed, 8 unresolved discussions (waiting on @sohrabtaee)

---

*[package.json, line 46 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG4YvmzCA0IJEKsuI4E:-LG4YvmzCA0IJEKsuI4F:bv7e216) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/ff813d2a976e5d90ecfbbf69e47a91e729480aff/package.json#L46)):*
> ```JSON
>   },
>   "dependencies": {
>     "gulp-line-ending-corrector": "^1.0.2"
> ```

Can be removed due to the comment above (about lint process in gulpfile.js).

---

*[src/vaadin-checkbox-group.html, line 93 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG4_9eR9D6Mu4aWzob7:-LG4_9eR9D6Mu4aWzob8:b-wwkty0) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/ff813d2a976e5d90ecfbbf69e47a91e729480aff/src/vaadin-checkbox-group.html#L93)):*
> ```HTML
>                 checkbox.disabled = true;
>               }
>               this._changeSelectedCheckbox(checkbox);
> ```

Nit: untested line of code.

---

*[src/vaadin-checkbox-group.html, line 148 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG4bWd27ZwJYQSiKZ00:-LG4bWd27ZwJYQSiKZ01:b-rl8ain) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/ff813d2a976e5d90ecfbbf69e47a91e729480aff/src/vaadin-checkbox-group.html#L148)):*
> ```HTML
>           // reflect the value array to checkboxes
>           this._checkboxes.forEach(checkbox => {
>             checkbox.checked = newV.includes(checkbox.value);
> ```

Seems to be causing issue with the build. Probably smth like `indexOf ` can be used instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)*

**Comment by sohrabtaee** [comment]
Review status: 10 of 14 files reviewed, 7 unresolved discussions (waiting on @YuriyVaadin and @tomivirkki)

---

*[vaadin-checkbox-group.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG07mPvCEeXiea3Lil1:-LGAT1xg4aeY_uk7yPIk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3cd33c6cf9efb813404498bce9395d90602597e7/vaadin-checkbox-group.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Missing an empty line
</blockquote></details>

Done.

---

*[demo/index.html, line 15 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG08W5_7ELBoE9nFOoR:-LGATOrh1kZW33PlNTtC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3cd33c6cf9efb813404498bce9395d90602597e7/demo/index.html#L15)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

All these need to be added to bower.json as devDependencies
</blockquote></details>

Done.

---

*[src/vaadin-checkbox-group.html, line 97 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG0U5Jl6qDVmE9THWL4:-LGATRjG6AGzAxHL02YI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3cd33c6cf9efb813404498bce9395d90602597e7/src/vaadin-checkbox-group.html#L97)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The coverage report fails because these two lines aren't tested
</blockquote></details>

Done.

---

*[src/vaadin-checkbox-group.html, line 148 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG4bWd27ZwJYQSiKZ00:-LGATT4cEd1nhV-_2Slf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3cd33c6cf9efb813404498bce9395d90602597e7/src/vaadin-checkbox-group.html#L148)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Seems to be causing issue with the build. Probably smth like `indexOf ` can be used instead.
</blockquote></details>

Done.

---

*[src/vaadin-checkbox-group.html, line 164 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG09KaFCO8TJp2MDuwb:-LGATZF80zq4aKIuqUOY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3cd33c6cf9efb813404498bce9395d90602597e7/src/vaadin-checkbox-group.html#L164)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Needs a new line
</blockquote></details>

Done.

---

*[gulpfile.js, line 6 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG05zqlApCef9toshTA:-LGATdUHAst-aWcrN3NB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3cd33c6cf9efb813404498bce9395d90602597e7/gulpfile.js#L6)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Please revert. Changes that concern all components should go trough skeleton. The lint process should also only validate without side-effects.
</blockquote></details>

Done.

---

*[package.json, line 46 at r1](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-LG4YvmzCA0IJEKsuI4E:-LGATemS1Bi07jbKjHph:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/3cd33c6cf9efb813404498bce9395d90602597e7/package.json#L46)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Can be removed due to the comment above (about lint process in gulpfile.js).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 10 of 15 files at r1, 6 of 6 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @YuriyVaadin)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-:-LGAXD-tCWEaJzOYGu36:bnfp4nl)*

**Comment by sohrabtaee** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @YuriyVaadin)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r2, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103#-:-LGOl4AD5HeHIIB45ujY:bnfp4nl)*

**Pull request merged**
