### PR TITLE
Set indeterminate to false when clicked the first time.

### LINKED ISSUE #59: In IE11 it takes two clicks to get out from indeterminate state
Live demo: https://www.webcomponents.org/element/vaadin/vaadin-checkbox/v2.0.0-alpha4

peek 2018-01-02 15-52

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #59

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/60)

### CODE REVIEW

**Comment by web-padawan** [comment]
BTW here is the link to the actual issue in Edge, it would be fine to mention that in the comment: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7344418/

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-:-L20eMKc0S7fZcoIO-d3:b-22qme6)*

**Comment by tomivirkki** [comment]
*[src/vaadin-checkbox.html, line 256 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-L20ergOOcK7AlBhqZi4:-L20ergOOcK7AlBhqZi5:bf60pbu) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/15014639d858df3358edcca1048c096f64c6dd70/src/vaadin-checkbox.html#L256)):*
> ```HTML
>                */
>               this.indeterminate = false;
>               this._nativeCheckbox.dispatchEvent(new CustomEvent('change'));
> ```

Why is this event needed? There should be tests to validate the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60)*

**Comment by vicsstar** [comment]
> https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7344418/
Yea, I was looking for that, thanks.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-:-L20fw8qzG3g7fVQcrQf:b-fmvp9a)*

**Comment by vicsstar** [comment]
*[src/vaadin-checkbox.html, line 256 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-L20ergOOcK7AlBhqZi4:-L20g4gabWUhLOxcwSXq:b-svuais) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/15014639d858df3358edcca1048c096f64c6dd70/src/vaadin-checkbox.html#L256)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this event needed? There should be tests to validate the change.
</blockquote></details>

Well I can write a test to validate it then; thought it was enough to test as per the issue itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60)*

**Comment by tomivirkki** [comment]
*[src/vaadin-checkbox.html, line 256 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-L20ergOOcK7AlBhqZi4:-L20iZCLfEJEVIburkyL:b-2klyo2) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/15014639d858df3358edcca1048c096f64c6dd70/src/vaadin-checkbox.html#L256)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Well I can write a test to validate it then; thought it was enough to test as per the issue itself.
</blockquote></details>

I'm mostly interested in _why_ the event is there in the first place. I'm curious since the indeterminate state seems to toggle off in IE with the line commented out, and all the tests pass as well (which is why I asked about the tests)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60)*

**Comment by vicsstar** [comment]
*[src/vaadin-checkbox.html, line 256 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-L20ergOOcK7AlBhqZi4:-L20oYFPK7VXB7F_7zoq:b8cgmxm) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/15014639d858df3358edcca1048c096f64c6dd70/src/vaadin-checkbox.html#L256)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I'm mostly interested in _why_ the event is there in the first place. I'm curious since the indeterminate state seems to toggle off in IE with the line commented out, and all the tests pass as well (which is why I asked about the tests)
</blockquote></details>

Seen. No need for the event. Not sure why it failed the first time without it.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60)*

**Comment by vicsstar** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-:-L24Rb3J9mYo0UvWeeQi:b-896fix)*

**Comment by vicsstar** [comment]
*[src/vaadin-checkbox.html, line 256 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-L20ergOOcK7AlBhqZi4:-L24RfSwoqH98iPzLjAA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/15014639d858df3358edcca1048c096f64c6dd70/src/vaadin-checkbox.html#L256)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Seen. No need for the event. Not sure why it failed the first time without it.

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-:-L24SWo3645GISvDqVd4:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/60#-:-L24TmtZvz6iIxKecTsb:bnfp4nl)*

**Pull request merged**
