### PR TITLE
Remove gray highlight when tapping disabled state

### PR DESCRIPTION
**Pull request by limonte**
Fixes https://github.com/vaadin/vaadin-checkbox/issues/20

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/22)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-checkbox.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/22#-KsnaBt1QG0zYE1nqPOb:-KsnaBt1QG0zYE1nqPOc:bwgp6ap) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/7c5e5252fb614ae3d09f436378952d5904ab8a02/vaadin-checkbox.html#L39)):*
> ```HTML
>       }
> 
>       :host([disabled]) {
> ```

Would consider this a functional style?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/22)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-checkbox.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/22#-KsnaBt1QG0zYE1nqPOb:-Ksr1IkXAMlqbe81MDUh:bb7867z) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/7c5e5252fb614ae3d09f436378952d5904ab8a02/vaadin-checkbox.html#L39)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Would consider this a functional style?
</blockquote></details>

Yup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/22)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/22#-:-Ksr25uJfoLTnCT0sFuZ:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/22#-:-Ksr2w7Qn0YcXremzSm9:bnfp4nl)*

**Pull request merged**
