### PR TITLE
Fixing visual test path, separate accessibility tests

### LINKED ISSUE #7: Disabled checkbox get invisible focus state
Reproducible here https://cdn.vaadin.com/vaadin-checkbox/1.0.0-alpha2/demo/index.html 

In the situation above I press TAB and expected result is:

Actiual result:

 

Chrome/Linux

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fix visual test path, separate accessibility tests

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/13)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-checkbox.html, line 130 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13#-KsJdXy-KCJ36St_ECo8:-KsJdXy-KCJ36St_ECo9:bjxwzap) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/448d75ed022ddb44630a0f728b0f0f77eb463767/vaadin-checkbox.html#L130)):*
> ```HTML
>              * True if the checkbox is disabled.
>              */
>             disabled: {
> ```

No need to define it, it's already defined in the control-state-mixin: https://github.com/vaadin/vaadin-control-state-mixin/blob/adc56509ccb3bac6e397b5733d85c5de3c3cf77f/vaadin-control-state-mixin.html#L69

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13)*

**Comment by limonte** [comment]
After removing the `disabled` property, please do `polymer analyze > analysis.json` and put updated `analysis.json` to separated commit which could be named `"Bump analysis.json"`

---

Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13#-:-KsN57jUGmmom0SP8dEu:b48r7cz)*

**Comment by YuriyVaadin** [comment]
Reviewed 1 of 5 files at r3.
Review status: 1 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-checkbox.html, line 130 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13#-KsJdXy-KCJ36St_ECo8:-KsNCQRIWNqJA2-n5KSw:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/448d75ed022ddb44630a0f728b0f0f77eb463767/vaadin-checkbox.html#L130)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

No need to define it, it's already defined in the control-state-mixin: https://github.com/vaadin/vaadin-control-state-mixin/blob/adc56509ccb3bac6e397b5733d85c5de3c3cf77f/vaadin-control-state-mixin.html#L69
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13)*

**Comment by limonte** [comment]
As discussed in person with @yuriyvaadin this fix should be done in `control-state-mixin` So, in this PR there shouldn't be any changes in `vaadin-checkbox.html`. Tests we've added age good though. The plan is:

- move this PR to the `in progress column`
- fix tabindex for disabled state in the `control-state-mixin`
- after merging the fix in the `control-state-mixin`, release a new patch version of  `control-state-mixin`
- update dependency, all tests introduced in this PR should pass

---

Review status: 1 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13#-:-KsNG_q3tRGeeZ5Rb-3j:b-mbo11c)*

**Comment by limonte** [comment]
:lgtm_strong: 

---

Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13#-:-KsOP-6q0Z3FHoX0iwaY:b-uwkowd)*

**Comment by limonte** [comment]
Reviewed 17 of 24 files at r2, 1 of 5 files at r3, 7 of 11 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13)*

**Comment by tomivirkki** [comment]
Reviewed 17 of 24 files at r2, 1 of 5 files at r3, 7 of 11 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13#-:-Ksbm02H0eO7h5HqXMUG:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
Reviewed 17 of 24 files at r2, 1 of 5 files at r3, 7 of 11 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/13)*

**Pull request merged**
