### PR TITLE
Disable hover effect on touch devices

### PR DESCRIPTION
**Pull request by jouni**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/61)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/valo/vaadin-checkbox.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61#-L21R3LBr6blZhCNI02U:-L21R3LBr6blZhCNI02V:b-jnu1kd) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/49dde3abb165d7381021f57663b5f36e1c080cb0/theme/valo/vaadin-checkbox.html#L153)):*
> ```HTML
> 
>       /* Disable hover for touch devices */
>       @media (pointer: coarse) {
> ```

BTW can we just edit media query instead of copying this complex selector?
```
 @media not all and (pointer: coarse) {  
   :host(:not([checked]):not([indeterminate]):not([disabled]):hover) [part="checkbox"] {
     background-color: var(--valo-contrast-30pct);
  }
}

```
Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61)*

**Comment by jouni** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/valo/vaadin-checkbox.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61#-L21R3LBr6blZhCNI02U:-L21spM7LlzMNUQgmRRL:bs8kt91) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/49dde3abb165d7381021f57663b5f36e1c080cb0/theme/valo/vaadin-checkbox.html#L153)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW can we just edit media query instead of copying this complex selector?
```
 @media not all and (pointer: coarse) {  
   :host(:not([checked]):not([indeterminate]):not([disabled]):hover) [part="checkbox"] {
     background-color: var(--valo-contrast-30pct);
  }
}

```
Not a blocker.
</blockquote></details>

Sure, if that works. My media query -fu was not strong enough. I just noticed that Firefox doesn’t understand @media (hover: hover) or @media (pointer: fine), and I wanted to have the hover styles for Firefox, but disabled on iOS and Android.

I’ll see if that works – we can then use the same in some other elements as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61)*

**Comment by jouni** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/valo/vaadin-checkbox.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61#-L21R3LBr6blZhCNI02U:-L21tm84_jMZ56iRnxp-:bee7c04) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/49dde3abb165d7381021f57663b5f36e1c080cb0/theme/valo/vaadin-checkbox.html#L153)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Sure, if that works. My media query -fu was not strong enough. I just noticed that Firefox doesn’t understand @media (hover: hover) or @media (pointer: fine), and I wanted to have the hover styles for Firefox, but disabled on iOS and Android.

I’ll see if that works – we can then use the same in some other elements as well.
</blockquote></details>

…aaand I tested it, and it doesn’t work in Firefox. It seems Firefox ignores the whole media query if it doesn’t understand some parts of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/valo/vaadin-checkbox.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61#-L21R3LBr6blZhCNI02U:-L21zgLRCdZG9vs9PQwA:bxqsdz) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/49dde3abb165d7381021f57663b5f36e1c080cb0/theme/valo/vaadin-checkbox.html#L153)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

…aaand I tested it, and it doesn’t work in Firefox. It seems Firefox ignores the whole media query if it doesn’t understand some parts of it.
</blockquote></details>

Ok let's keep it as is then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-checkbox/61#-:-L21znZ2U94NMxRLGDnM:bnfp4nl)*

**Pull request merged**
