### PR TITLE
Prepare for P3

### LINKED ISSUE #75: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #75

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/79)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 13 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[package.json, line 25 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-L8gIryUET2EDqMTRKjq:-L8gIryUET2EDqMTRKjr:bbbx2sc) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/9e1e46f5102c904c364954bee32313f69620ea78/package.json#L25)):*
> ```JSON
>   },
>   "devDependencies": {
>     "bower": "latest",
> ```

BTW travis uses global `bower`, so we can remove it here too.

Not a blocker, but we've done this on other elements, would be nice to align.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79)*

**Comment by tomivirkki** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 25 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-L8gIryUET2EDqMTRKjq:-L8gOAsy1857mHrUpiOY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/9e1e46f5102c904c364954bee32313f69620ea78/package.json#L25)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW travis uses global `bower`, so we can remove it here too.

Not a blocker, but we've done this on other elements, would be nice to align.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-:-L8gObZz7ZCTOmqG-w51:bnfp4nl)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[.npmignore, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-L8gOu33CJHDRsH3R7qU:-L8gOu33CJHDRsH3R7qV:b-ow7758) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/e90766e0eee373889a17e0ea739c66aba448902b/.npmignore#L11)):*
> ```
> gulpfile.js
> index.html
> screenshot.png
> ```

I guess `test` and `demo` folders should be ignored.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79)*

**Comment by tomivirkki** [comment]
*[.npmignore, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-L8gOu33CJHDRsH3R7qU:-L8gQMCKAomyc7RqJf6L:b-ivb68p) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/e90766e0eee373889a17e0ea739c66aba448902b/.npmignore#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I guess `test` and `demo` folders should be ignored.
</blockquote></details>

The tests are required by for example control-state-mixin test suite. This is the set from skeleton.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.npmignore, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-L8gOu33CJHDRsH3R7qU:-L8gU8F5E-r8lz472ZsH:b-sltbv6) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/e90766e0eee373889a17e0ea739c66aba448902b/.npmignore#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The tests are required by for example control-state-mixin test suite. This is the set from skeleton.
</blockquote></details>

I hope it's not too late reconsider using `.npmignore`: https://github.com/vaadin/vaadin-element-skeleton/pull/111

Users won't be happy wasting their time and bandwidth by downloading demos and other unnecessary files.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.npmignore, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-L8gOu33CJHDRsH3R7qU:-L8gVpZs4EpG--1NYs98:bkk3ka8) ([raw file](https://github.com/vaadin/vaadin-checkbox/blob/e90766e0eee373889a17e0ea739c66aba448902b/.npmignore#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I hope it's not too late reconsider using `.npmignore`: https://github.com/vaadin/vaadin-element-skeleton/pull/111

Users won't be happy wasting their time and bandwidth by downloading demos and other unnecessary files.
</blockquote></details>

Not a blocker, we'll revisit this after releasing all P3 components.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-checkbox/79#-:-L8gW48v2hKs5GOSjvCL:bnfp4nl)*

**Pull request merged**
