### PR TITLE
Add lumo-checkbox-switch theme

### LINKED ISSUE #90: Toggle switch theme
What about including a toggle switch theme for `vaadin-checkbox`?

This is for example a CSS-only theme:

screen shot 2018-05-14 at 12 23 35

Fiddle: https://jsfiddle.net/heruan/g0tx9f29/

### PR DESCRIPTION
**Pull request by heruan**
Closes #90 

Preview: https://jsfiddle.net/heruan/g0tx9f29/

Play with it: https://jsfiddle.net/heruan/g0tx9f29/4/

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-checkbox/96)

### CODE REVIEW

**Comment by jouni** [comment]
TBH, I don’t really know if it’s a good idea to implement this “only” with a theme instead of promoting it into its own component.

The benefit of having it as a separate component would be easier discoverability, as we could list it separately on vaadin.com.

But on the other hand, having this available right now would make some users very happy.

So, if feasible, I would ship this now in the themes (need to implement it for Material as well but in a separate PR), and then start thinking about making it as a standalone component. When that would be released, these theme variants could be marked as deprecated in favor of that component.

**Comment by web-padawan** [comment]
Pros for making it separate component:

> The expected user experience of a switch button is for an immediate action to take place. For instance, toggling a light/dark theme for a site or application, where the theme change instantly takes effect.

> In contrast, when interacting with a checkbox, any change in UI state is typically expected to occur after a purposeful form submission by the user. See related WCAG success criteria "on input".

See https://github.com/scottaohara/aria-switch-button

**Comment by jouni** [comment]
@web-padawan, implementation-wise it sounds like it doesn’t make a difference. It’s up to the developer to hook up the event listener for the switch component and react accordingly.

But as a design-guideline that’s correct. And to make that more obvious, a separate component is preferred so we can have those guidelines separately. Thanks for pointing that out, so we have a good reason to make it into a separate component.

I still stand by my previous comment, though 🙂

**Comment by web-padawan** [comment]
@jouni I have tried prototyping Material theme and so far it looks we would need to have a different shadow parts structure to be able to apply proper styling. Below are the results as my research:
markup: https://github.com/web-padawan/lit-components/blob/master/packages/switch-base/lit-switch-base.js
styles: https://github.com/web-padawan/lit-components/blob/master/packages/switch-material/lit-switch-material-styles.js

**Comment by jouni** [comment]
> I have tried prototyping Material theme and so far it looks we would need to have a different shadow parts structure to be able to apply proper styling.

Challenge accepted 😅

**Comment by web-padawan** [comment]
In terms of API, the `[part="track"]` and `[part="thumb"]` parts are more descriptive than `[part="checkbox"]` and `[part="checkbox"]::after` used here for Lumo. 

Note the 2 compromises I still had to make in my implementation:
1. the `thumb-underlay` part is only needed for Material theme, and its purpose is to provide a ripple with proper opacity in a way which wouldn't affect the opacity of the thumb
2. the `[part="track"]::after` is used for the same purpose for background (applying opacity for the part itself would again affect the thumb).

In case you have a better solution, I would be happy to apply it.

**Comment by jouni** [comment]
Here’s one possible implementation, which should be using the structure we currently have: 
http://jsbin.com/nireyisari/edit?html,css,js,output

Not a full implementation, it’s missing at least the `focus-ring` and keyboard `active` styles. Did I miss something else important?

**Comment by jouni** [comment]
Agree on the API, the names are not accurate. We are bending the component to a different shape, kind of abusing the fact that we know the internal implementation details.

> proper opacity in a way which wouldn't affect the opacity of the thumb

Ah, I missed that. Hmm…

**Comment by web-padawan** [comment]
Yes, you can check how the MD implementation works, and I have tried to align mine with it:
https://material-components.github.io/material-components-web-catalog/#/component/switch
https://material.io/develop/web/components/input-controls/switches/

**Comment by jouni** [comment]
Easy fix for the ripple being over the toggle, though – added `z-index: -1;` for the pseudo-elements.

**Comment by web-padawan** [comment]
It has been a while since this PR was submitted. Apologies about keeping it open for so long without any progress.

The component has been converted to Polymer 3 so there are merge commits that would be tricky to solve.
Also, the new development for Vaadin web components will happen in the [monorepo](https://github.com/vaadin/vaadin-web-components).

I'm closing this now. We will submit a new PR to the monorepo when the linked issue is prioritised.

**Pull request closed without merging**
